=== OneDecision/one-decision/test/src/main/resources/schema/testCases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (x64) (http://www.altova.com) by Bruce Silver (private) -->
<xs:schema xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.omg.org/spec/DMN/20160719/testcase" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="testCases">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="modelName" type="xs:string" minOccurs="0"/>
				<xs:element name="labels" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="testCase" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string" />
							<xs:element name="inputNode" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="valueType">
											<xs:attribute name="name" use="required"/>
											<xs:attribute name="type" type="xs:string"/>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="resultNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="computed" type="valueType" minOccurs="0"/>
										<xs:element name="expected" type="valueType" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="name" use="required"/>
									<xs:attribute name="type" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="valueType">
		<xs:choice>
			<xs:element name="value" type="xs:anySimpleType"/>
			<xs:element name="component" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="valueType">
							<xs:attribute name="name" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="list">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="item" type="valueType" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== OneDecision/one-decision/test/src/test/resources/compliance-level-2/0003-input-data-string-allowed-values/0003-input-data-string-allowed-values-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0003-input-data-string-allowed-values.dmn</modelName>
	<labels>
		<label>base</label>
		<label>simple type</label>
	</labels>
	<testCase id="001"> 
		<description>Testing valid input</description>
		<inputNode name="Employment Status">
			<value>EMPLOYED</value>
		</inputNode>
		<resultNode name="Employment Status Statement" type="decision">
			<computed>
				<value>You are EMPLOYED</value>
			</computed>
		</resultNode>
	</testCase>
	<testCase id="002">
		<description>Testing invalid input</description>
		<!-- is the following number type override valid? -->
		<inputNode name="Employment Status" type="feel:number">
			<value>10</value>
		</inputNode>
		<!-- how do we test for invalid result? -->
	</testCase>
	<testCase id="003">
		<description>Testing value that is not in the allowed values list</description>
		<inputNode name="Employment Status">
			<value>FOO</value>
		</inputNode>
		<!-- how do we test for invalid result? -->
	</testCase>
	
</testCases>

=== OneDecision/one-decision/test/src/test/resources/compliance-level-2/0001-input-data-string/0001-input-data-string-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0001-input-data-string.dmn</modelName>
	<labels>
		<label>base</label>
		<label>simple type</label>
	</labels>
	<testCase id="001"> 
		<description>Testing valid input</description>
		<inputNode name="Full Name">
			<value>John Doe</value>
		</inputNode>
		<resultNode name="Greeting Message" type="decision">
			<computed>
				<value>Hello John Doe</value>
			</computed>
		</resultNode>
	</testCase>
	<testCase id="002">
		<description>Testing invalid input</description>
		<!-- is the following number type override valid? -->
		<inputNode name="Full Name" type="feel:number">
			<value>10</value>
		</inputNode>
		<!-- how do we test for invalid result? -->
	</testCase>
</testCases>

=== OneDecision/one-decision/test/src/test/resources/compliance-level-2/0002-input-data-number/0002-input-data-number-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0002-input-data-number.dmn</modelName>
	<labels>
		<label>base</label>
		<label>simple type</label>
	</labels>
	<testCase id="001"> 
		<description>Testing valid input</description>
		<inputNode name="Monthly Salary">
			<value>10000</value>
		</inputNode>
		<resultNode name="Yearly Salary" type="decision">
			<computed>
				<value>120000</value>
			</computed>
		</resultNode>
	</testCase>
	<testCase id="002">
		<description>Testing invalid input</description>
		<!-- is the following number type override valid? -->
		<inputNode name="Monthly Salary" type="feel:string">
			<value>foo</value>
		</inputNode>
		<!-- how do we test for invalid result? -->
	</testCase>
</testCases>
